version: "3.8"
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      # Используем имя сервиса "db" вместо localhost – так контейнер найдет базу по сети docker-compose.
      DATABASE_URL: "postgresql+asyncpg://myuser:mypassword@db:5432/mydb"
      PYTHONPATH: "/app"
    depends_on:
      - db
    # По умолчанию uvicorn запускается на 8000 порту, пробрасываем его наружу.
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    restart: always
    # Монтируем локальный конфигурационный файл nginx.
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
